In [1]:
import numpy as np 


In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
data  = np.array([[0.5,1.5,2.0],[1.0,2.0,1.0]])
labels = np.array([0.0,1.0,0.0]).reshape(1,3)

landa = 0.01
learning_rate = 0.1


w1 = np.array([[0.2,-0.3],[0.4 , 0.1]])
b1 = np.array([0.1,-0.2]).reshape((2,1))

w2 = np.array([0.3,-0.5]).reshape((2,1))
b2 = np.array([0.05]).reshape((1,1))



In [4]:
def forward(data,w1,b1,w2,b2):
    z1 = w1.T @ data + b1 
    a1 = sigmoid(z1)
    print('a1 : ', a1,'\n ---')
    z2 =  w2.T @ a1 + b2  
    a2 = sigmoid(z2) 
    print('a2 : ', a2,'\n ---')
    return a1,a2
    

def cost(predicted , label,landa):
    m = labels.shape[1]
    l2 = (landa/(2*m)) * (np.sum(w1* w1)+np.sum(w2*w2)) 
    loss = - (label *np.log( predicted) + (1-label) * np.log(1-predicted))
    return np.mean(loss) + l2    

In [5]:
a1 , predictions = forward(data,w1,b1,w2,b2)
print ("cost is ", cost(predictions,labels,landa))

a1 :  [[0.64565631 0.76852478 0.7109495 ]
 [0.4378235  0.38936077 0.33181223]] 
 ---
a2 :  [[0.50619597 0.52145608 0.52432546]] 
 ---
cost is  0.7009893919459316


In [6]:
def backward(data,w1,w2,a2,a1,labels): 
    m = labels.shape[1]
    dz2 =  a2 - labels 
    dw2 = ((1/m)* (a1 @ dz2.T)) + ((landa/m)*(w2))
    db2 = np.mean(dz2)
    da1 =   w2 @ dz2  
    dz1 = da1 * a1 *(1- a1)
    dw1 = ((1/m )*  data @ dz1.T) + ((landa/m)*(w1))
    db1  = np.mean(dz1,axis=1).reshape((2,1)) 
    return dw2 , db2 ,dw1,db1  


In [7]:
def train(data,w1,w2,b1,b2,epochs,learning_rate,landa):
    for i in range(epochs):
        print(f'epoch {i+1} :')
        a1 , a2 = forward(data,w1,b1,w2,b2)
        print ("cost is ", cost(a2,labels,landa))
        dw2 , db2 , dw1 , db1 = backward(data,w1,w2,a2,a1,labels)
        w1 -= learning_rate * dw1
        w2 -= learning_rate * dw2
        b1 -= learning_rate * db1
        b2 -= learning_rate * db2 
        print("updated weights w1\n",w1 , "\nb1:\n",b1,"\nw2:\n ", w2,'\nb2:\n',b2)



In [8]:
train(data,w1,w2,b1,b2,3,learning_rate,landa)


epoch 1 :
a1 :  [[0.64565631 0.76852478 0.7109495 ]
 [0.4378235  0.38936077 0.33181223]] 
 ---
a2 :  [[0.50619597 0.52145608 0.52432546]] 
 ---
cost is  0.7009893919459316
updated weights w1
 [[ 0.19847626 -0.2978312 ]
 [ 0.39933369  0.10018809]] 
b1:
 [[ 0.09861572]
 [-0.19788227]] 
w2:
  [[ 0.28883918]
 [-0.5068092 ]] 
b2:
 [[0.03160075]]
epoch 2 :
a1 :  [[0.64501259 0.76763367 0.70990072]
 [0.43865812 0.39072806 0.3332868 ]] 
 ---
a2 :  [[0.49889742 0.51382119 0.5169273 ]] 
 ---
cost is  0.6958673142841637
updated weights w1
 [[ 0.19706267 -0.29574618]
 [ 0.39874567  0.10025999]] 
b1:
 [[ 0.09732586]
 [-0.19582172]] 
w2:
  [[ 0.2782244 ]
 [-0.51334582]] 
b2:
 [[0.01394589]]
epoch 3 :
a1 :  [[0.64442056 0.7668146  0.7089308 ]
 [0.43944007 0.3919981  0.33468873]] 
 ---
a2 :  [[0.49191438 0.50651509 0.5098429 ]] 
 ---
cost is  0.6911723976554675
updated weights w1
 [[ 0.19575045 -0.29374445]
 [ 0.3982284   0.10021754]] 
b1:
 [[ 0.09612316]
 [-0.19381817]] 
w2:
  [[ 0.2681306 ]
 [-0.519