In [2]:
import numpy as np

In [3]:
a1 = np.array([[1,2],[3,4],[5,6]])
a1.shape

(3, 2)

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a2.shape

(2, 3)

In [5]:
r1 = a2 @ a1
r1

array([[22, 28],
       [49, 64]])

In [6]:
r2 = a1 @ a2
r2

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [7]:
r3 = 5 * a1
r3

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [10]:
r4 = a2 * a2
r4

array([[ 1,  4,  9],
       [16, 25, 36]])