In [22]:
import numpy as np
import tensorflow as tf


In [9]:
# Define a 1x3 matrix (row vector)
x = np.array([[0.23, 0.45, 0.67]])
x.shape

(1, 3)

In [10]:
# Define a 3x4 matrix
w_1 = np.array([
    [0.45, -0.12, 0.78, 0.72],
    [0.05, 0.35, -0.22 ,-0.85],
    [-0.55,0.11, 0.67,0.45],
])
w_1.shape

(3, 4)

In [63]:
b_1 = np.array([0.1,-0.1,0.2,-0.2])

In [36]:
# Perform matrix multiplication
z_1 = x@w_1 +b
z_1 #array([[-0.1425,  0.1036,  0.7293, -0.1154]])


array([[-0.1425,  0.1036,  0.7293, -0.1154]])

In [44]:
a_1 = tf.keras.activations.tanh(z_1)
a_1 = a_1.numpy()
a_1

array([[-0.14154322,  0.10323094,  0.62263691, -0.11489045]])

In [45]:
w_2 = np.array([0.25,-0.35,0.15,0.05])
b_2 = np.array([0.3])

In [53]:
z_2 = a_1@w_2.T + b_2
z_2

array([0.31613438])

In [57]:
y_hat = tf.keras.activations.sigmoid(z_2).numpy()
y_hat

array([0.57838188])

In [58]:
# Calculate log loss
y=1 
log_loss = - (y*np.log(y_hat) + (1-y)*np.log(1-y_hat))
log_loss

array([0.54752093])

In [62]:
dw_1 = (y-y_hat)* (w_2)*(1-a_1**2)*x.T 
dw_1

array([[ 0.02375734, -0.03357857,  0.00890675,  0.00478461],
       [ 0.04648176, -0.0656972 ,  0.01742624,  0.00936119],
       [ 0.06920618, -0.09781583,  0.02594574,  0.01393777]])

In [ ]:
db_1 = (y-y_hat)* (w_2)*(1-a_1**2) 
db_1 

array([[ 0.1032928 , -0.14599378,  0.03872499,  0.02080264]])

In [66]:
dw_2 = (y-y_hat)*a_1
dw_2

array([[-0.05967719,  0.04352403,  0.262515  , -0.04843989]])

In [68]:
db_2 = (y-y_hat)
db_2

array([0.42161812])