In [1]:
import numpy as np
import tensorflow as tf


2025-03-09 10:06:25.566285: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-09 10:06:25.566346: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-09 10:06:25.566361: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-09 10:06:26.511433: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# Define a 1x3 matrix (row vector)
x = np.array([[0.23, 0.45, 0.67]])
x.shape

(1, 3)

In [3]:
# Define a 3x4 matrix
w_1 = np.array([
    [0.45, -0.12, 0.78, 0.72],
    [0.05, 0.35, -0.22 ,-0.85],
    [-0.55,0.11, 0.67,0.45],
])
w_1.shape

(3, 4)

In [4]:
b_1 = np.array([0.1,-0.1,0.2,-0.2])

In [5]:
# Perform matrix multiplication
z_1 = x@w_1 +b_1
z_1 #array([[-0.1425,  0.1036,  0.7293, -0.1154]])


array([[-0.1425,  0.1036,  0.7293, -0.1154]])

In [6]:
a_1 = tf.keras.activations.tanh(z_1)
a_1 = a_1.numpy()
a_1

2025-03-09 10:07:06.474069: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-03-09 10:07:08.702119: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2025-03-09 10:07:08.702564: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

array([[-0.14154322,  0.10323094,  0.62263691, -0.11489045]])

In [7]:
w_2 = np.array([0.25,-0.35,0.15,0.05])
b_2 = np.array([0.3])

In [8]:
z_2 = a_1@w_2.T + b_2
z_2

array([0.31613438])

In [9]:
y_hat = tf.keras.activations.sigmoid(z_2).numpy()
y_hat

array([0.57838188])

In [10]:
# Calculate log loss
y=1 
log_loss = - (y*np.log(y_hat) + (1-y)*np.log(1-y_hat))
log_loss

array([0.54752093])

In [11]:
dw_1 = (y-y_hat)* (w_2)*(1-a_1**2)*x.T 
dw_1

array([[ 0.02375734, -0.03357857,  0.00890675,  0.00478461],
       [ 0.04648176, -0.0656972 ,  0.01742624,  0.00936119],
       [ 0.06920618, -0.09781583,  0.02594574,  0.01393777]])

In [12]:
db_1 = (y-y_hat)* (w_2)*(1-a_1**2) 
db_1 

array([[ 0.1032928 , -0.14599378,  0.03872499,  0.02080264]])

In [13]:
dw_2 = (y-y_hat)*a_1
dw_2

array([[-0.05967719,  0.04352403,  0.262515  , -0.04843989]])

In [14]:
db_2 = (y-y_hat)
db_2

array([0.42161812])

In [15]:
lr = 0.01

In [16]:
w_2_u = w_2 - lr * dw_2
w_2_u

array([[ 0.25059677, -0.35043524,  0.14737485,  0.0504844 ]])

In [17]:
b_2_u = b_2 - lr * db_2
b_2_u

array([0.29578382])

In [18]:
w_1_u = w_1 - lr * dw_1
w_1_u 

array([[ 0.44976243, -0.11966421,  0.77991093,  0.71995215],
       [ 0.04953518,  0.35065697, -0.22017426, -0.85009361],
       [-0.55069206,  0.11097816,  0.66974054,  0.44986062]])

In [19]:
b_1_u = b_1 - lr * db_1
b_1_u

array([[ 0.09896707, -0.09854006,  0.19961275, -0.20020803]])